None
2025-05-05 20:49:20,982 - easytorch-sweep - INFO - Launching EasyTorch HPO with wandb sweeps.
DESCRIPTION: An Example Config
GPU_NUM: 1
RUNNER: <class 'basicts.runners.runner_zoo.simple_prob_tsf_runner.SimpleProbTimeSeriesForecastingRunner'>
USE_WANDB: False
DATASET:
  NAME: ETTh1
  TYPE: <class 'basicts.data.simple_tsf_dataset.TimeSeriesForecastingDataset'>
  PARAM:
    dataset_name: ETTh1
    train_val_test_ratio: [0.6, 0.2, 0.2]
    input_len: 336
    output_len: 96
SCALER:
  TYPE: <class 'basicts.scaler.min_max_scaler.MinMaxScaler'>
  PARAM:
    dataset_name: ETTh1
    train_ratio: 0.6
    norm_each_channel: True
    rescale: False
MODEL:
  NAME: PatchTST
  ARCH: <class 'baselines.PatchTST.arch.patchtst_arch.PatchTST'>
  PARAM:
    enc_in: 7
    seq_len: 336
    pred_len: 96
    e_layers: 3
    n_heads: 4
    d_model: 16
    d_ff: 128
    dropout: 0.3
    fc_dropout: 0.3
    head_dropout: 0.0
    patch_len: 16
    stride: 8
    individual: 1
    padding_patch: end
    revin: 0
    affine: 0
    subtract_last: 1
    decomposition: 1
    kernel_size: 25
    head_type: probabilistic
    distribution_type: gaussian
    quantiles: []
  FORWARD_FEATURES: [0]
  TARGET_FEATURES: [0]
METRICS:
  FUNCS:
    NLL: nll_loss
    CRPS: crps
  TARGET: NLL
  NULL_VAL: nan
TRAIN:
  RESUME_TRAINING: False
  EARLY_STOPPING_PATIENCE: 10
  NUM_EPOCHS: 100
  CKPT_SAVE_DIR: checkpoints/gaussian_PatchTST/ETTh1_100_336_96
  LOSS: nll_loss
  OPTIM:
    TYPE: Adam
    PARAM:
      lr: 0.0002
      weight_decay: 0.0001
  LR_SCHEDULER:
    TYPE: MultiStepLR
    PARAM:
      milestones: [1, 25]
      gamma: 0.5
  CLIP_GRAD_PARAM:
    max_norm: 5.0
  DATA:
    BATCH_SIZE: 64
    SHUFFLE: True
VAL:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 64
TEST:
  INTERVAL: 1
  DATA:
    BATCH_SIZE: 64
EVAL:
  USE_GPU: True

wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
wandb: ERROR Error while calling W&B API: Sweep kai-reffert-university-mannheim/Prob_LTSF/61z2gxlt is not running (<Response [400]>)
wandb: ERROR Sweep kai-reffert-university-mannheim/Prob_LTSF/61z2gxlt is not running
Traceback (most recent call last):
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 134, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 402, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kreffert/Probabilistic_LTSF/BasicTS/experiments/hp_tuning.py", line 36, in <module>
    main()
  File "/home/kreffert/Probabilistic_LTSF/BasicTS/experiments/hp_tuning.py", line 31, in main
    basicts.launch_sweep(args.cfg, path, args.sweep_id)
  File "/home/kreffert/Probabilistic_LTSF/BasicTS/basicts/launcher.py", line 366, in launch_sweep
    wandb.agent(sweep_id, function=agent_function, project=project, entity=entity) #count=count)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/wandb_agent.py", line 566, in agent
    return pyagent(sweep_id, function, entity, project, count)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 356, in pyagent
    agent.run()
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 327, in run
    self._setup()
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 135, in _setup
    self._register()
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/agents/pyagent.py", line 112, in _register
    agent = self._api.register_agent(socket.gethostname(), sweep_id=self._sweep_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/apis/internal.py", line 158, in register_agent
    return self.api.register_agent(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/apis/normalize.py", line 65, in wrapper
    raise err
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/apis/normalize.py", line 25, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 3144, in register_agent
    response = self.gql(
               ^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 374, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 150, in __call__
    retry_timedelta_triggered = check_retry_fn(e)
                                ^^^^^^^^^^^^^^^^^
  File "/home/kreffert/miniconda3/envs/BasicTS/lib/python3.11/site-packages/wandb/util.py", line 855, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.errors.UsageError: Sweep kai-reffert-university-mannheim/Prob_LTSF/61z2gxlt is not running
